import argon2 from "argon2"; import crypto from "node:crypto"; import { prisma } from "../config/prisma.js"; import { cookieOptions } from "../config/session.js"; import { sendPasswordSetupEmail } from "../services/emailService.js";
const safeUser = user => ({ id: user.id, name: user.name, email: user.email, phone: user.phone, role: user.role, mustChangePassword: user.mustChangePassword, tutorProfile: user.tutorProfile || null });
export async function register(req, res, next) { try { const { name, email, password } = req.validated; const existing = await prisma.user.findUnique({ where: { email: email.toLowerCase() } }); if (existing) return res.status(409).json({ message: "An account already exists for this email." }); const passwordHash = await argon2.hash(password); const user = await prisma.user.create({ data: { name, email: email.toLowerCase(), passwordHash, role: "STUDENT" } }); req.session.regenerate(error => { if (error) return next(error); req.session.userId = user.id; res.status(201).json({ user: safeUser(user) }); }); } catch (e) { next(e); } }
export async function login(req, res, next) { try { const { email, password } = req.validated; const user = await prisma.user.findUnique({ where: { email: email.toLowerCase() } }); if (!user?.passwordHash || user.status !== "ACTIVE" || !(await argon2.verify(user.passwordHash, password))) return res.status(401).json({ message: "Invalid email or password" }); req.session.regenerate(error => { if (error) return next(error); req.session.userId = user.id; res.json({ user: safeUser(user) }); }); } catch (e) { next(e); } }
export const me = (req, res) => res.json({ user: safeUser(req.user) });
export const logout = (req, res, next) => req.session.destroy(error => error ? next(error) : res.clearCookie("institute.sid", { httpOnly: cookieOptions.httpOnly, secure: cookieOptions.secure, sameSite: cookieOptions.sameSite }).status(204).end());
export async function changePassword(req, res, next) { try { const user = await prisma.user.findUnique({ where: { id: req.user.id } }); if (!user?.passwordHash || !(await argon2.verify(user.passwordHash, req.validated.currentPassword))) return res.status(400).json({ message: "Current password is incorrect." }); const passwordHash = await argon2.hash(req.validated.newPassword); await prisma.user.update({ where: { id: user.id }, data: { passwordHash, mustChangePassword: false } }); res.json({ message: "Password changed successfully." }); } catch (error) { next(error); } }
export async function updateProfile(req,res,next){try{const {name,phone,expertise,bio}=req.validated;const user=await prisma.user.update({where:{id:req.user.id},data:{name,phone:phone||null,...(req.user.role==="TUTOR"?{tutorProfile:{upsert:{create:{expertise:expertise||null,bio:bio||null},update:{expertise:expertise||null,bio:bio||null}}}}:{})},include:{tutorProfile:true}});res.json({user:safeUser(user),message:"Profile updated."});}catch(error){next(error);}}
export async function forgotPassword(req,res,next){try{const email=req.validated.email.toLowerCase();const user=await prisma.user.findUnique({where:{email}});if(user){const token=crypto.randomBytes(32).toString("hex");const tokenHash=crypto.createHash("sha256").update(token).digest("hex");await prisma.passwordSetupToken.deleteMany({where:{userId:user.id,usedAt:null}});await prisma.passwordSetupToken.create({data:{userId:user.id,tokenHash,expiresAt:new Date(Date.now()+60*60*1000)}});await sendPasswordSetupEmail({email,setupUrl:`${process.env.CLIENT_URL.split(",")[0].replace(/\/$/,"")}/reset-password?token=${token}`});}res.json({message:"If that email is registered, a password reset link has been sent."});}catch(error){next(error);}}
export async function resetPassword(req,res,next){try{const tokenHash=crypto.createHash("sha256").update(req.validated.token).digest("hex");const record=await prisma.passwordSetupToken.findUnique({where:{tokenHash}});if(!record||record.usedAt||record.expiresAt<new Date())return res.status(400).json({message:"This password reset link is invalid or has expired."});const passwordHash=await argon2.hash(req.validated.newPassword);await prisma.$transaction([prisma.user.update({where:{id:record.userId},data:{passwordHash,mustChangePassword:false}}),prisma.passwordSetupToken.update({where:{id:record.id},data:{usedAt:new Date()}})]);res.json({message:"Password reset successfully. You can now sign in."});}catch(error){next(error);}}
